### ISSUE TITLE
[Question] Imperative code in abstract base-class instead?

### ISSUE THREAD

**Issue by Liander** [davidfowl/uController#12]
@davidfowl Just learned about this project when listening to 'ASP.NET Community Standup'. Very cool! It was an interesting discussion around having an architecture with using imperative structure in a light-weight framework that requires a lot of user code but that comes with easier debugging vs declarative structure with somewhat invisible framework with less user code that is harder to debug. And then approach that with having declarative code transpiled into imperative code was very cool to see. 

It got me thinking though if not another way to achieve the goal of getting more insight is to have the orchestration of the middleware/filters in a controller-base-class, where the first entry might be `CanHandle()` that is required in your user controller/handler so you get early entry-point and can step from there. If then the base class is provided by code instead of inside the framework assembly then you could potentially achieve the same thing, do you think? Is the orchestration too complex to be handled in base-class? I have never seen if it possible to deliver code-file alongside an assembly either, but I wanted to mention what got into my mind when watching the episode.

Anyway, good work!

**Comment by davidfowl** [comment]
I think it would be too complex to stick into a base class. You basically need to figure out the interaction between the framework and the user code and figure out which pieces to generate and which pieces to leave in a library.
