### ISSUE TITLE
[Question] Is there any way to use Razor pages or .cshtml with AOT? 

### ISSUE THREAD

**Issue by kurtcodemander** [davidfowl/uController#19]
I'm not sure where to ask so I just ask here. 

builder.Services.AddRazorPages() and app.MapRazorPages() in a new ASP.NET Core Web App makes AOT app fail. 

Is there any way at all to make .cshtml work in an AOT app?

**Comment by davidfowl** [comment]
No, more fundamental changes are needed to make that work.

**Comment by kurtcodemander** [comment]
Thanks, I'll just close.
